<a href="https://colab.research.google.com/github/DulanMahesh/ComputerVision/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

In [24]:
#Numpy basics

#Converting python Lists to numpy Arrays

py_list =[1,2,3,4,5,6,7]
np_array =np.array(py_list)
print(np_array)

[1 2 3 4 5 6 7]


In [26]:
py_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

np_array= np.array(py_list)

print(np_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
#print first row
print(format(np_array[0]))

[1 2 3]


In [37]:
print(format(np_array[0, :]))    #  : Refers to all columns in that first row

[1 2 3]


In [38]:
#print forst column
print(format(np_array[:, 0]))

[ 1  4  7 10]


In [39]:
#print 3rd row 2nd column element

print(format(np_array[2, 1]))

8


In [40]:
# print 2nd row onwards and 2nd column onwards

print(format(np_array[1:, 1:]))

[[ 5  6]
 [ 8  9]
 [11 12]]


In [42]:
# print last 2 rows and last 2 columns

print(format(np_array[-2:, -2:]))

[[ 8  9]
 [11 12]]


In [43]:
#print 3rd ,1st and 4th row

print(format(np_array[[2, 0, 3]]))

Array with 3rd, 1st, and 4th row:
[[ 7  8  9]
 [ 1  2  3]
 [10 11 12]]



In [44]:
#print 1st and 3rd column

print(format(np_array[:, [0, 2]]))

[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


In [46]:
#create convienient function to print array information

def array_info(array):
  print('Array:\n{}'.format(array))
  print('Data type:\t{}'.format(array.dtype))
  print('Array shape:\t{}\n'.format(array.shape))

In [47]:
array_info(np_array)

Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Data type:	int64
Array shape:	(4, 3)



In [51]:
#creates a NumPy array of integers from 0 to 9 with the data type specified as int64

# Sequence array.
array = np.arange(10, dtype=np.int64)   # here 0 is including and 10 is excluding in the result set

array_info(array)

Array:
[0 1 2 3 4 5 6 7 8 9]
Data type:	int64
Array shape:	(10,)



In [52]:
# Sequence array.starting from 5 to 10 in the steps of 2
array = np.arange(5, 10, 2, dtype=np.float32)
array_info(array)

Array:
[5. 7. 9.]
Data type:	float32
Array shape:	(3,)

