<a href="https://colab.research.google.com/github/DulanMahesh/ComputerVision/blob/main/Numpy_part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#element wise operations

a =np.random.random((4,4)) #generates a 4x4 array with random floating-point numbers between 0 and 1.

print(a)
print("shape:",a.shape)
print("dimension:",a.ndim)






[[0.26028168 0.81569166 0.3309147  0.15656424]
 [0.0394611  0.35059348 0.24764973 0.95711965]
 [0.96162726 0.24452728 0.5766827  0.38051605]
 [0.98716596 0.79530606 0.99722809 0.21132455]]
shape: (4, 4)
dimension: 2


In [2]:
b = np.random.random((4,4))
print(b)
print("shape:",b.shape)
print("dimension:",b.ndim)

[[0.66491502 0.98709803 0.58139245 0.4062257 ]
 [0.70232912 0.25506993 0.46511195 0.64843676]
 [0.28454289 0.7337466  0.99688559 0.0184524 ]
 [0.99472787 0.16929877 0.63293546 0.41238823]]
shape: (4, 4)
dimension: 2


In [3]:
# element wise scalar operations

#element wise scalar addition

a+5


array([[5.26028168, 5.81569166, 5.3309147 , 5.15656424],
       [5.0394611 , 5.35059348, 5.24764973, 5.95711965],
       [5.96162726, 5.24452728, 5.5766827 , 5.38051605],
       [5.98716596, 5.79530606, 5.99722809, 5.21132455]])

In [4]:
#element wise scalar subtraction

a-4

array([[-3.73971832, -3.18430834, -3.6690853 , -3.84343576],
       [-3.9605389 , -3.64940652, -3.75235027, -3.04288035],
       [-3.03837274, -3.75547272, -3.4233173 , -3.61948395],
       [-3.01283404, -3.20469394, -3.00277191, -3.78867545]])

In [5]:
#element wise scalar multipication

a/10


array([[0.02602817, 0.08156917, 0.03309147, 0.01565642],
       [0.00394611, 0.03505935, 0.02476497, 0.09571196],
       [0.09616273, 0.02445273, 0.05766827, 0.03805161],
       [0.0987166 , 0.07953061, 0.09972281, 0.02113245]])

In [6]:

# element wise array operations - for this to be happen both arrays should be in the same shape

#array addition

a+b



array([[0.9251967 , 1.80278969, 0.91230716, 0.56278995],
       [0.74179022, 0.60566341, 0.71276168, 1.60555641],
       [1.24617015, 0.97827388, 1.57356829, 0.39896845],
       [1.98189383, 0.96460483, 1.63016355, 0.62371278]])

In [7]:
#array subtraction

a-b

array([[-0.40463335, -0.17140637, -0.25047775, -0.24966146],
       [-0.66286802,  0.09552355, -0.21746221,  0.30868289],
       [ 0.67708437, -0.48921932, -0.42020289,  0.36206366],
       [-0.00756192,  0.62600729,  0.36429263, -0.20106368]])

In [8]:
#array multiplication

a*b



array([[0.1730652 , 0.80516763, 0.19239131, 0.06360042],
       [0.02771468, 0.08942586, 0.11518485, 0.62063156],
       [0.2736242 , 0.17942106, 0.57488667, 0.00702143],
       [0.98196149, 0.13464433, 0.63118102, 0.08714776]])

In [9]:
#array division
a/b

array([[ 0.39145104,  0.82635325,  0.56917612,  0.38541196],
       [ 0.05618605,  1.37449946,  0.53245189,  1.47604163],
       [ 3.37955116,  0.33325848,  0.57848434, 20.6214965 ],
       [ 0.99239801,  4.69764827,  1.57556047,  0.51244078]])

In [10]:
#Broadcasting

A= np.array([[1,2,3],[4,5,6,],[7,8,9,]])
print (A)
print("shape:",A.shape)
print("dimension:",A.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
dimension: 2


In [11]:
B=np.array([0,1,0])
print(B)
print("shape:",B.shape)
print("dimension:",B.ndim)

[0 1 0]
shape: (3,)
dimension: 1


In [12]:
print("array A + array B:")
a+b  # here A and B are both same shape. so array b will be boradcast to A # 0 1 0
                                                                           # 0 1 0
                                                                           # 0 1 0

array A + array B:


array([[0.9251967 , 1.80278969, 0.91230716, 0.56278995],
       [0.74179022, 0.60566341, 0.71276168, 1.60555641],
       [1.24617015, 0.97827388, 1.57356829, 0.39896845],
       [1.98189383, 0.96460483, 1.63016355, 0.62371278]])

In [13]:

#lINEAR ALGEBRA

#Transpose

a =np.array([[5,4,2],[7,8,9]]) #2*3 array
print(a)
print("shape:",a.shape)
print("dimension:",a.ndim)

[[5 4 2]
 [7 8 9]]
shape: (2, 3)
dimension: 2


In [14]:
#now transpose it(make the array into 3*2)

a_transpose = a.transpose() #transpose it

print(a_transpose)
print("shape:",a_transpose.shape)
print("dimension:",a_transpose.ndim)



[[5 7]
 [4 8]
 [2 9]]
shape: (3, 2)
dimension: 2


In [15]:
#MATRIX MULTIPLICATION

# matrix multiplication using 'np.matmul'

a=np.random.random((3,4)) # To carry out the mtrix multiplication using np.matmul , no of columns in the first matrix should be equal to the unmber of rows in the seconf matrix(In this example, 4 columns in first matrix =4rows in second matrix)
print (a)
print("shape:",a.shape)
print("dimension:",a.ndim)

[[0.79790416 0.33904778 0.82662537 0.86344155]
 [0.25704097 0.053209   0.92981352 0.20586105]
 [0.06385733 0.21933019 0.13954248 0.13088214]]
shape: (3, 4)
dimension: 2


In [16]:
b = np.random.random((4,2))
print (b)
print("shape:",b.shape)
print("dimension:",b.ndim)

[[0.36168917 0.27831748]
 [0.54980418 0.64729997]
 [0.58195336 0.01402578]
 [0.59735742 0.20658462]]
shape: (4, 2)
dimension: 2


In [17]:
# lets multiply the matrix using np.matmul

c =np.matmul(a,b)
print(c)
print("shape:",c.shape)
print("dimension:",c.ndim)

[[1.4718438  0.6315041 ]
 [0.78630418 0.16155026]
 [0.30307579 0.18874047]]
shape: (3, 2)
dimension: 2


In [ ]:
# using '@' operator

a = np.random.random((3,4))
print (a)
print("shape:",a.shape)
print("dimension:",a.ndim)


[[0.21313569 0.76322905 0.34543841 0.34905243]
 [0.47281156 0.80765493 0.64007313 0.98040472]
 [0.54514999 0.87181284 0.85974847 0.32452716]]
shape: (3, 4)
dimension: 2


In [19]:
b= np.random.random((4,2))
print(b)
print("shape:",b.shape)
print("dimension:",b.ndim)

[[0.44043764 0.10377503]
 [0.81679959 0.56283783]
 [0.79204173 0.41243351]
 [0.86083033 0.57737368]]
shape: (4, 2)
dimension: 2


In [20]:

# matrix multiplication between  a and b matrixes

c= a@b
print(c)
print("shape:",c.shape)
print("dimension:",c.ndim)


[[1.29135472 0.79569641]
 [2.21886297 1.33369228]
 [1.91252043 1.08922473]]
shape: (3, 2)
dimension: 2


In [21]:
#Matrix inverse


a =np.random.random((3,3))
print(a)
print("shape:",a.shape)
print("dimension:",a.ndim)

[[0.30218537 0.36671657 0.00444047]
 [0.92451383 0.09445403 0.16366919]
 [0.63480184 0.5766326  0.28062489]]
shape: (3, 3)
dimension: 2


In [22]:
# lets find out the inverse of the matrix

a_inverse =np.linalg.inv(a)
print(a_inverse)
print("shape:",a_inverse.shape)
print("dimension:",a_inverse.ndim)

[[ 0.89955703  1.33002473 -0.78994609]
 [ 2.06157417 -1.0865846   0.60110873]
 [-6.2710451  -0.7759185   4.11524562]]
shape: (3, 3)
dimension: 2


In [23]:
#Dot product between two vectors

a =np.array([1,2,3])
print(a)
print("shape:",a.shape)
print("dimension:",a.ndim)

[1 2 3]
shape: (3,)
dimension: 1


In [24]:
b =np.array([4,5,6])
print(b)
print("shape:",b.shape)
print("dimension:",b.ndim)

[4 5 6]
shape: (3,)
dimension: 1


In [25]:
# now lets calculate dot product ((1*4)+(2*5)+(3*6))

c =np.dot(a,b)
print(c)
print("shape:",c.shape)
print("dimension:",c.ndim)

32
shape: ()
dimension: 0


In [26]:
# Array statistics


#sum

a = np.array([1, 2, 3, 4, 5])

print(a.sum())

15


In [27]:
#sum along axis

a =np.array([[1,2,3],[4,5,6]])
print(a)
print("shape:",a.shape)
print("dimension:",a.ndim)

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
dimension: 2


In [28]:
print("sum alnog axis 0 :", a.sum(axis=0)) # (1+4) (2+5) (3+6)


print("sum alnog axis 1 :", a.sum(axis=1)) #(1+2+3) (4+5+6)

sum alnog axis 0 : [5 7 9]
sum alnog axis 1 : [ 6 15]
