<a href="https://colab.research.google.com/github/DulanMahesh/ComputerVision/blob/main/Numpy_part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#element wise operations

a =np.random.random((4,4)) #generates a 4x4 array with random floating-point numbers between 0 and 1.

print(a)
print("shape:",a.shape)
print("dimension:",a.ndim)






[[0.97164788 0.75607841 0.78299283 0.95827872]
 [0.56384023 0.09634332 0.81368942 0.51935418]
 [0.68660256 0.76992677 0.50244506 0.1992667 ]
 [0.11597554 0.83601591 0.6486797  0.71486795]]
shape: (4, 4)
dimension: 2


In [3]:
b = np.random.random((4,4))
print(b)
print("shape:",b.shape)
print("dimension:",b.ndim)

[[0.85080041 0.17358035 0.04689916 0.1946547 ]
 [0.52656159 0.26604709 0.81637332 0.80457998]
 [0.10874549 0.55495934 0.01372211 0.54232191]
 [0.89174019 0.51435526 0.08969494 0.57920273]]
shape: (4, 4)
dimension: 2


In [4]:
# element wise scalar operations

#element wise scalar addition

a+5


array([[5.97164788, 5.75607841, 5.78299283, 5.95827872],
       [5.56384023, 5.09634332, 5.81368942, 5.51935418],
       [5.68660256, 5.76992677, 5.50244506, 5.1992667 ],
       [5.11597554, 5.83601591, 5.6486797 , 5.71486795]])

In [5]:
#element wise scalar subtraction

a-4

array([[-3.02835212, -3.24392159, -3.21700717, -3.04172128],
       [-3.43615977, -3.90365668, -3.18631058, -3.48064582],
       [-3.31339744, -3.23007323, -3.49755494, -3.8007333 ],
       [-3.88402446, -3.16398409, -3.3513203 , -3.28513205]])

In [6]:
#element wise scalar multipication

a/10


array([[0.09716479, 0.07560784, 0.07829928, 0.09582787],
       [0.05638402, 0.00963433, 0.08136894, 0.05193542],
       [0.06866026, 0.07699268, 0.05024451, 0.01992667],
       [0.01159755, 0.08360159, 0.06486797, 0.07148679]])

In [7]:

# element wise array operations - for this to be happen both arrays should be in the same shape

#array addition

a+b



array([[1.82244829, 0.92965876, 0.82989199, 1.15293342],
       [1.09040182, 0.3623904 , 1.63006274, 1.32393417],
       [0.79534806, 1.3248861 , 0.51616717, 0.74158861],
       [1.00771574, 1.35037117, 0.73837463, 1.29407068]])

In [8]:
#array subtraction

a-b

array([[ 0.12084746,  0.58249806,  0.73609367,  0.76362402],
       [ 0.03727864, -0.16970377, -0.00268391, -0.2852258 ],
       [ 0.57785707,  0.21496743,  0.48872295, -0.34305521],
       [-0.77576465,  0.32166066,  0.55898476,  0.13566522]])

In [9]:
#array multiplication

a*b



array([[0.82667841, 0.13124035, 0.03672171, 0.18653346],
       [0.29689661, 0.02563186, 0.66427433, 0.41786198],
       [0.07466493, 0.42727805, 0.00689461, 0.1080667 ],
       [0.10342005, 0.43000918, 0.05818329, 0.41405347]])

In [10]:
#array division
a/b

array([[ 1.14203973,  4.35578347, 16.69524122,  4.92296725],
       [ 1.07079636,  0.36212881,  0.9967124 ,  0.64549727],
       [ 6.31384844,  1.38735708, 36.61571987,  0.36743251],
       [ 0.1300553 ,  1.62536672,  7.23206572,  1.23422751]])

In [11]:
#Broadcasting

A= np.array([[1,2,3],[4,5,6,],[7,8,9,]])
print (A)
print("shape:",A.shape)
print("dimension:",A.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
dimension: 2


In [12]:
B=np.array([0,1,0])
print(B)
print("shape:",B.shape)
print("dimension:",B.ndim)

[0 1 0]
shape: (3,)
dimension: 1


In [13]:
print("array A + array B:")
a+b  # here A and B are both same shape. so array b will be boradcast to A # 0 1 0
                                                                           # 0 1 0
                                                                           # 0 1 0

array A + array B:


array([[1.82244829, 0.92965876, 0.82989199, 1.15293342],
       [1.09040182, 0.3623904 , 1.63006274, 1.32393417],
       [0.79534806, 1.3248861 , 0.51616717, 0.74158861],
       [1.00771574, 1.35037117, 0.73837463, 1.29407068]])

In [14]:

#lINEAR ALGEBRA

#Transpose

a =np.array([[5,4,2],[7,8,9]]) #2*3 array
print(a)
print("shape:",a.shape)
print("dimension:",a.ndim)

[[5 4 2]
 [7 8 9]]
shape: (2, 3)
dimension: 2


In [15]:
#now transpose it(make the array into 3*2)

a_transpose = a.transpose() #transpose it

print(a_transpose)
print("shape:",a_transpose.shape)
print("dimension:",a_transpose.ndim)



[[5 7]
 [4 8]
 [2 9]]
shape: (3, 2)
dimension: 2


In [16]:
#MATRIX MULTIPLICATION

# matrix multiplication using 'np.matmul'

a=np.random.random((3,4)) # To carry out the mtrix multiplication using np.matmul , no of columns in the first matrix should be equal to the unmber of rows in the seconf matrix(In this example, 4 columns in first matrix =4rows in second matrix)
print (a)
print("shape:",a.shape)
print("dimension:",a.ndim)

[[0.73799625 0.33208    0.14661166 0.01891861]
 [0.84495721 0.62828015 0.66727858 0.53917347]
 [0.97803183 0.66541096 0.03407669 0.54662336]]
shape: (3, 4)
dimension: 2


In [17]:
b = np.random.random((4,2))
print (b)
print("shape:",b.shape)
print("dimension:",b.ndim)

[[0.65697523 0.25911424]
 [0.36196386 0.96817322]
 [0.25303682 0.41618251]
 [0.27849087 0.57676832]]
shape: (4, 2)
dimension: 2


In [18]:
# lets multiply the matrix using np.matmul

c =np.matmul(a,b)
print(c)
print("shape:",c.shape)
print("dimension:",c.ndim)

[[0.64741302 0.58466516]
 [1.1015316  1.41591231]
 [1.04424968 1.2271122 ]]
shape: (3, 2)
dimension: 2


In [19]:
# using '@' operator

a = np.random.random((3,4))
print (a)
print("shape:",a.shape)
print("dimension:",a.ndim)


[[0.27314045 0.13570395 0.321505   0.97959643]
 [0.74183081 0.70572558 0.21274496 0.96449838]
 [0.79461584 0.5883145  0.58446765 0.06879401]]
shape: (3, 4)
dimension: 2


In [20]:
b= np.random.random((4,2))
print(b)
print("shape:",b.shape)
print("dimension:",b.ndim)

[[0.54651481 0.82710839]
 [0.36892551 0.31760384]
 [0.97681371 0.36674821]
 [0.5238993  0.18302241]]
shape: (4, 2)
dimension: 2


In [21]:

# matrix multiplication between  a and b matrixes

c= a@b
print(c)
print("shape:",c.shape)
print("dimension:",c.ndim)


[[1.02660032 0.56621633]
 [1.37889391 1.09226429]
 [1.2582707  1.07102769]]
shape: (3, 2)
dimension: 2


In [22]:
#Matrix inverse


a =np.random.random((3,3))
print(a)
print("shape:",a.shape)
print("dimension:",a.ndim)

[[0.36112786 0.92170932 0.23505642]
 [0.16536471 0.5909093  0.41605607]
 [0.46455073 0.12594916 0.57535948]]
shape: (3, 3)
dimension: 2


In [23]:
# lets find out the inverse of the matrix

a_inverse =np.linalg.inv(a)
print(a_inverse)
print("shape:",a_inverse.shape)
print("dimension:",a_inverse.ndim)

[[ 2.13535241 -3.71784466  1.81608814]
 [ 0.72866802  0.73199236 -0.82700985]
 [-1.88361308  2.84158628  0.45275371]]
shape: (3, 3)
dimension: 2


In [24]:
#Dot product between two vectors

a =np.array([1,2,3])
print(a)
print("shape:",a.shape)
print("dimension:",a.ndim)

[1 2 3]
shape: (3,)
dimension: 1


In [25]:
b =np.array([4,5,6])
print(b)
print("shape:",b.shape)
print("dimension:",b.ndim)

[4 5 6]
shape: (3,)
dimension: 1


In [26]:
# now lets calculate dot product ((1*4)+(2*5)+(3*6))

c =np.dot(a,b)
print(c)
print("shape:",c.shape)
print("dimension:",c.ndim)

32
shape: ()
dimension: 0


In [27]:
# Array statistics


#sum

a = np.array([1, 2, 3, 4, 5])

print(a.sum())

15


In [28]:
#sum along axis

a =np.array([[1,2,3],[4,5,6]])
print(a)
print("shape:",a.shape)
print("dimension:",a.ndim)

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
dimension: 2


In [29]:
print("sum alnog axis 0 :", a.sum(axis=0)) # (1+4) (2+5) (3+6)


print("sum alnog axis 1 :", a.sum(axis=1)) #(1+2+3) (4+5+6)

sum alnog axis 0 : [5 7 9]
sum alnog axis 1 : [ 6 15]


In [30]:
#Min and max values

a = np.array([-1.1, 2, 5, 100])

print('Minimum = ', a.min())
print('Maximum = ', a.max())

Minimum =  -1.1
Maximum =  100.0


In [31]:
#Min and max along the axis

a =np.array([[1,-2,5],[2,3,-7]])

print("Minimum value along axis 0:" , a.min(axis=0))
print("Minimum value along axis 1:" , a.min(axis=1))


print("Max value along axis 0:" , a.max(axis=0))
print("Max value along axis 1:" , a.max(axis=1))

Minimum value along axis 0: [ 1 -2 -7]
Minimum value along axis 1: [-2 -7]
Max value along axis 0: [2 3 5]
Max value along axis 1: [5 3]


In [33]:


# Mean and standard deviation

data =np.array([1.2,2,3,5.0,3.3,1.4,5.6])

print('Mean = ', data.mean())
print('Standard Deviation = ', data.std())

print('Mean of the array               = {:8.6f}'.format(data.mean())) #8.6f specifies the format for floating-point numbers:8 indicates a minimum width of 8 characters (for alignment)..6f means 6 digits after the decimal point.
print('Standard deviation of the array = {:8.6f}'.format(data.std()))

Mean =  3.0714285714285716
Standard Deviation =  1.5862933305704354
Mean of the array               = 3.071429
Standard deviation of the array = 1.586293


In [34]:
# standardizing an array

data =np.array([1.2,2,3,5.0,3.3,1.4,5.6])

print('Array              = ', data)
print('Mean               = {:8.6f}'.format(data.mean()))
print('Standard deviation = {:8.6f}'.format(data.std()))
print()


Array              =  [1.2 2.  3.  5.  3.3 1.4 5.6]
Mean               = 3.071429
Standard deviation = 1.586293



In [35]:
standardizing_array =(data -data.mean())/data.std()

print('Standardized array = ', standardizing_array)
print('Mean               = {:8.6f}'.format(standardizing_array.mean()))
print('Standard deviation = {:8.6f}'.format(standardizing_array.std()))

Standardized array =  [-1.17974938 -0.67542903 -0.0450286   1.21577226  0.14409153 -1.05366929
  1.59401252]
Mean               = -0.000000
Standard deviation = 1.000000
