<a href="https://colab.research.google.com/github/DulanMahesh/ComputerVision/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

In [24]:
#Numpy basics

#Converting python Lists to numpy Arrays

py_list =[1,2,3,4,5,6,7]
np_array =np.array(py_list)
print(np_array)

[1 2 3 4 5 6 7]


In [26]:
py_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

np_array= np.array(py_list)

print(np_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
#print first row
print(format(np_array[0]))

[1 2 3]


In [37]:
print(format(np_array[0, :]))    #  : Refers to all columns in that first row

[1 2 3]


In [38]:
#print forst column
print(format(np_array[:, 0]))

[ 1  4  7 10]


In [39]:
#print 3rd row 2nd column element

print(format(np_array[2, 1]))

8


In [40]:
# print 2nd row onwards and 2nd column onwards

print(format(np_array[1:, 1:]))

[[ 5  6]
 [ 8  9]
 [11 12]]


In [42]:
# print last 2 rows and last 2 columns

print(format(np_array[-2:, -2:]))

[[ 8  9]
 [11 12]]


In [43]:
#print 3rd ,1st and 4th row

print(format(np_array[[2, 0, 3]]))

Array with 3rd, 1st, and 4th row:
[[ 7  8  9]
 [ 1  2  3]
 [10 11 12]]



In [44]:
#print 1st and 3rd column

print(format(np_array[:, [0, 2]]))

[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


In [46]:
#create convienient function to print array information

def array_info(array):
  print('Array:\n{}'.format(array))
  print('Data type:\t{}'.format(array.dtype))
  print('Array shape:\t{}\n'.format(array.shape))

In [47]:
array_info(np_array)

Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Data type:	int64
Array shape:	(4, 3)



In [51]:
#creates a NumPy array of integers from 0 to 9 with the data type specified as int64

# Sequence array.
array = np.arange(10, dtype=np.int64)   # here 0 is including and 10 is excluding in the result set

array_info(array)

Array:
[0 1 2 3 4 5 6 7 8 9]
Data type:	int64
Array shape:	(10,)



In [52]:
# Sequence array.starting from 5 to 10 in the steps of 2
array = np.arange(5, 10, 2, dtype=np.float32)
array_info(array)

Array:
[5. 7. 9.]
Data type:	float32
Array shape:	(3,)



In [57]:
#linespace -to Returns num evenly spaced samples, calculated over the interval

linespace = np.linspace(0, 5, 7, dtype=np.float32)   # 7 elements between 0 and 5
print(linespace)

[0.        0.8333333 1.6666666 2.5       3.3333333 4.1666665 5.       ]


In [58]:
# Zeros array -To Creates array filled with zeros

zeros = np.zeros((2, 3), dtype=np.float32)
array_info(zeros)

Array:
[[0. 0. 0.]
 [0. 0. 0.]]
Data type:	float32
Array shape:	(2, 3)



In [59]:
#ones array

ones =np.ones((2,3))
array_info(ones)

Array:
[[1. 1. 1.]
 [1. 1. 1.]]
Data type:	float64
Array shape:	(2, 3)



In [60]:
# Constant array/matrix.
array = np.full((3, 3), 3.14)  # constant array means display number is constant
array_info(array)

Array:
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]
Data type:	float64
Array shape:	(3, 3)



In [61]:
#Identity array where All the diagonal elements (from the top left to the bottom right) are 1 and All the non-diagonal elements are 0

identity = np.eye(5, dtype=np.float32)  # Identity matrix of shape 5x5
array_info(identity)



Array:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Data type:	float32
Array shape:	(5, 5)



In [62]:
#Random integers array

rand_int =np.random.randint(0,10,(2,3))

print(rand_int)

[[3 8 0]
 [7 1 0]]


In [63]:
#Random array of 5*5 float elements

# Random array/matrix.
random_array = np.random.random((5, 5))   # Random array of shape 5x5.
array_info(random_array)

Array:
[[0.10030457 0.72363905 0.31236922 0.28657208 0.1226605 ]
 [0.76146733 0.07187825 0.9491626  0.85155099 0.09015555]
 [0.26795434 0.18247066 0.08678181 0.11374145 0.53253845]
 [0.31166625 0.6792181  0.24546613 0.01541897 0.06293065]
 [0.35424378 0.90859675 0.75387625 0.94084818 0.29731167]]
Data type:	float64
Array shape:	(5, 5)



In [64]:
# boolian array(cordinate with previously developed random_array)

bool_array =random_array>0.5 # true if the random_array element is larger than 0.5

print(bool_array)

[[False  True False False False]
 [ True False  True  True False]
 [False False False False  True]
 [False  True False False False]
 [False  True  True  True False]]


In [67]:
# Data type conversion

age_in_years =np.random.randint(0,100,10)    # first create array of 10 random integers between 0 and 99.

array_info(age_in_years)

Array:
[95 84 37 93 41 93 84 94 76 43]
Data type:	int64
Array shape:	(10,)



In [68]:
# convert int64 data type to uint8 data type

age_in_years =age_in_years.astype(np.uint8)
array_info(age_in_years)

Array:
[95 84 37 93 41 93 84 94 76 43]
Data type:	uint8
Array shape:	(10,)



In [73]:
# Mathematical functions

#exponenetial function -To Calculate the exponential of all elements in the input array.
array = np.array([np.full(3, -1), np.zeros(3), np.ones(3)]) # create a 3x3 matrix where 1st,2nd and 3rd rows are filled with -1 ,0,+1 respective;y
array_info(array)




Array:
[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]
Data type:	float64
Array shape:	(3, 3)



In [75]:
exp_array = np.exp(array) # The NumPy function np.exp() computes the exponent of Euler's number e=2.718 raised to the power of each element in the input array

array_info(exp_array)

Array:
[[0.36787944 0.36787944 0.36787944]
 [1.         1.         1.        ]
 [2.71828183 2.71828183 2.71828183]]
Data type:	float64
Array shape:	(3, 3)



In [77]:
#Square root function(sqrt)

array = np.arange(10)      #array will contain integers starting from 0 up to 9, resulting in a 1D array with 10 elements.
array_info(array)

root_array = np.sqrt(array)# this gives the square root value for the each given element.notice the data type is also changed
array_info(root_array)

Array:
[0 1 2 3 4 5 6 7 8 9]
Data type:	int64
Array shape:	(10,)

Array:
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
Data type:	float64
Array shape:	(10,)



In [79]:
#Logrithm

array = np.array([0, np.exp(1), np.exp(1)**2, 1, 10]) # The first element is simply 0, The second element is e is euler number which is 2.718, the 3rd element is euler number * euler number which is 7.3890, 4th element is 1 and 5th element is 10
array_info(array)

print('Logrithm:')
log_array = np.log(array)
array_info(log_array)

Array:
[ 0.          2.71828183  7.3890561   1.         10.        ]
Data type:	float64
Array shape:	(5,)

Logrithm:
Array:
[      -inf 1.         2.         0.         2.30258509]
Data type:	float64
Array shape:	(5,)



<ipython-input-79-1d073e995467>:7: RuntimeWarning: divide by zero encountered in log
  log_array = np.log(array)


In [81]:
# Power -Returns first array elements raised to powers from second array, element-wise.

array = np.arange(0, 6, dtype=np.int64)
array_info(array)

pow_array = np.power(array, 3) # gives the power of 3 for the each element
array_info(pow_array)

Array:
[0 1 2 3 4 5]
Data type:	int64
Array shape:	(6,)

Array:
[  0   1   8  27  64 125]
Data type:	int64
Array shape:	(6,)



In [82]:
# Clip values
array = np.random.random((3, 3))      #generates a 3x3 array of random floating-point numbers between 0 and 1.
array_info(array)

Array:
[[0.87461818 0.38342598 0.0481729 ]
 [0.25013001 0.81578776 0.82213144]
 [0.14250276 0.19574546 0.45129442]]
Data type:	float64
Array shape:	(3, 3)



In [84]:
# Clipped between 0.2 and 0.5

cliped_array = np.clip(array, 0.2, 0.5) # . Any value below 0.2 is set to 0.2.Any value above 0.5 is set to 0.5.but Values that fall between 0.2 and 0.5 remain unchanged
array_info(cliped_array)

Array:
[[0.5        0.38342598 0.2       ]
 [0.25013001 0.5        0.5       ]
 [0.2        0.2        0.45129442]]
Data type:	float64
Array shape:	(3, 3)



In [85]:
# Clipped to 0.2

cliped_array = np.clip(array, 0.2, np.inf) # Any value less than 0.2 will be clipped to 0.2.but Any value greater than or equal to 0.2 will remain unchanged (because there is no upper bound(positive infinity)).
array_info(cliped_array)

Array:
[[0.87461818 0.38342598 0.2       ]
 [0.25013001 0.81578776 0.82213144]
 [0.2        0.2        0.45129442]]
Data type:	float64
Array shape:	(3, 3)

