<a href="https://colab.research.google.com/github/DulanMahesh/ComputerVision/blob/main/TensorFlow_Basics_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import random
import matplotlib.pyplot as plt

In [2]:
SEED_VALUE = 42

# Fix random number seed.
random.seed(SEED_VALUE)
np.random.seed(SEED_VALUE)
tf.random.set_seed(SEED_VALUE)

In [3]:
#create two constant tensors
tensor1 = tf.constant([[1, 2, 3], [4, 5, 6]])
tensor2 = tf.constant([[7, 8, 9], [10, 11, 12]])

print(tensor1)
print(tensor2)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


In [4]:
#concatanate rensors along axix 0

print(tf.concat([tensor1,tensor2],axis=0))

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


In [5]:
#concatanate tensors along axis1

print (tf.concat([tensor1,tensor2],axis=1))

tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [6]:
#tensor flow variables

# Create a tensor variable.
tensor = tf.Variable([2, 4])

# You must use the assign() method to assign a new value to a tensorflow variable
tensor[0].assign(42)
print(tensor[0])

print(tensor[1])


tf.Tensor(42, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [7]:
#tensorflow reduce functions

# these functions start with the name 'reduce' (e.g., reduce_sum() instead of just sum()).

# Create some data.
x = 10 * tf.random.uniform(shape=[3,5])
print(x)

tf.Tensor(
[[6.6456213  4.4100676  3.528825   4.6448255  0.33660412]
 [6.8467236  7.4011745  8.724445   2.2632635  2.2319686 ]
 [3.103881   7.223358   1.3318717  5.4806385  5.746088  ]], shape=(3, 5), dtype=float32)


In [8]:
# Compute the following quantities for all axes..
xmin  = tf.reduce_min (x)
xmax  = tf.reduce_max (x)
xmean = tf.reduce_mean(x)
xsum  = tf.reduce_sum (x)

print('\nComputed over all axes:\n')
print('min:  ', xmin)
print('max:  ', xmax)
print('mean: ', xmean)
print('sum:  ', xsum)


Computed over all axes:

min:   tf.Tensor(0.33660412, shape=(), dtype=float32)
max:   tf.Tensor(8.724445, shape=(), dtype=float32)
mean:  tf.Tensor(4.6612906, shape=(), dtype=float32)
sum:   tf.Tensor(69.91936, shape=(), dtype=float32)


In [9]:
# Compute the quantities for axis = 1(column wise)
xmin  = tf.reduce_min (x, axis=1)
xmax  = tf.reduce_max (x, axis=1)
xmean = tf.reduce_mean(x, axis=1)
xsum  = tf.reduce_sum (x, axis=1)

print('\nComputed for axis 1:\n')
print('min:  ', xmin)
print('max:  ', xmax)
print('mean: ', xmean)
print('sum:  ', xsum)


Computed for axis 1:

min:   tf.Tensor([0.33660412 2.2319686  1.3318717 ], shape=(3,), dtype=float32)
max:   tf.Tensor([6.6456213 8.724445  7.223358 ], shape=(3,), dtype=float32)
mean:  tf.Tensor([3.913189  5.493515  4.5771675], shape=(3,), dtype=float32)
sum:   tf.Tensor([19.565945 27.467575 22.885838], shape=(3,), dtype=float32)


In [10]:
#compute the quantitiess for axis=0 (row wise)

xmin =tf.reduce_min(x,axis=0)
xmax =tf.reduce_max(x,axis=0)
xmean=tf.reduce_mean(x,axis=0)
xsum =tf.reduce_sum(x,axis=0)

print('\nComputed for axis 0:\n')
print('min:  ', xmin)
print('max:  ', xmax)
print('mean: ', xmean)
print('sum:  ', xsum)


Computed for axis 0:

min:   tf.Tensor([3.103881   4.4100676  1.3318717  2.2632635  0.33660412], shape=(5,), dtype=float32)
max:   tf.Tensor([6.8467236 7.4011745 8.724445  5.4806385 5.746088 ], shape=(5,), dtype=float32)
mean:  tf.Tensor([5.5320754 6.3448663 4.528381  4.1295757 2.7715538], shape=(5,), dtype=float32)
sum:   tf.Tensor([16.596226 19.0346   13.585142 12.388727  8.314661], shape=(5,), dtype=float32)


In [11]:
# tensor flow indexing (gather)

##first lets see how numpy array indexing is done
# Create some data.
num_data = 24
data = np.random.uniform(0, 10, num_data)#it create 24 data points in between 0 and 10.also uniform distribution means that all values in a given range have an equal chance of being selected.
print('data: \n', data)
print('\n')

# Create an array of random indices.
indices = np.random.choice(data.shape[0], 5, replace=False)
print('indices: ', indices)
print('\n')

# Use the indices array to select the corresponding elements from the data array.
selected_data = data[indices]

print('selected_data: ', selected_data)


data: 
 [3.74540119 9.50714306 7.31993942 5.98658484 1.5601864  1.5599452
 0.58083612 8.66176146 6.01115012 7.08072578 0.20584494 9.69909852
 8.32442641 2.12339111 1.81824967 1.8340451  3.04242243 5.24756432
 4.31945019 2.9122914  6.11852895 1.39493861 2.92144649 3.66361843]


indices:  [ 0  5 20 15 13]


selected_data:  [3.74540119 1.5599452  6.11852895 1.8340451  2.12339111]


In [12]:
#tensor flow array indexing

# Create some data.
num_data = 24
data = tf.random.uniform(shape=[num_data])
print('data: \n', data)
print('\n')

# Create an array of random indices.
indices = tf.random.uniform([5], minval=0, maxval=len(data)-1, dtype=tf.dtypes.int32)
print('indices: ', indices)
print('\n')

# Use this he gather() method to index one tensor by another tensor.
selected_data = tf.gather(data, indices)

print('selected_data: ', selected_data)


data: 
 tf.Tensor(
[0.68789124 0.48447883 0.9309944  0.252187   0.73115396 0.89256823
 0.94674826 0.7493341  0.34925628 0.54718256 0.26160395 0.69734323
 0.11962581 0.53484344 0.7148968  0.87501776 0.33967495 0.17377627
 0.4418521  0.9008261  0.13803864 0.12217975 0.5754491  0.9417181 ], shape=(24,), dtype=float32)


indices:  tf.Tensor([ 6  3  2 15  1], shape=(5,), dtype=int32)


selected_data:  tf.Tensor([0.94674826 0.252187   0.9309944  0.87501776 0.48447883], shape=(5,), dtype=float32)


In [27]:
#How to select specific rows within rank-2 sensor (or Matrix)

# lets create a random ranked -2 tensor(or Matrix)

tensor = tf.random.normal(shape=[5, 3])
print(tensor)
print('\n')

#create a tensor with indices

rows = tf.constant([0, 2, 4])
cols = tf.constant([0, 2])

print('rows: \n', rows)
print('cols: \n', cols)
print('\n')

print('1st, 3rd, and 5th rows of the tensor is following:')

# Access specific rows of a tensor by specifying the  indices of the rows along with the row axis.
print(tf.gather(tensor, rows, axis=0))

print('\n')
print('1st and 3rd columns of the tensor is following, cols:')
# Access specific cols of a tensor by specifying the indices of the cols along with the col axis.
print(tf.gather(tensor, cols, axis=1))



tf.Tensor(
[[-1.5440757   1.3154334   0.7808076 ]
 [ 1.0706282  -0.9656791   0.25132167]
 [-1.8545105   1.4713811  -0.7334912 ]
 [-0.34491098 -0.7662992   1.3054299 ]
 [-0.0578156   0.17457157  0.17278242]], shape=(5, 3), dtype=float32)


rows: 
 tf.Tensor([0 2 4], shape=(3,), dtype=int32)
cols: 
 tf.Tensor([0 2], shape=(2,), dtype=int32)


1st, 3rd, and 5th rows of the tensor is following:
tf.Tensor(
[[-1.5440757   1.3154334   0.7808076 ]
 [-1.8545105   1.4713811  -0.7334912 ]
 [-0.0578156   0.17457157  0.17278242]], shape=(3, 3), dtype=float32)


1st and 3rd columns of the tensor is following, cols:
tf.Tensor(
[[-1.5440757   0.7808076 ]
 [ 1.0706282   0.25132167]
 [-1.8545105  -0.7334912 ]
 [-0.34491098  1.3054299 ]
 [-0.0578156   0.17278242]], shape=(5, 2), dtype=float32)


In [29]:
# 4. numpy/tensorflow interpoerability

#following built-in functions that allow you to convert back and forth between and NumPy and TensorFlow
#tf.convert_to_tensor(python_object)   ------------->>python object to tensorflow
#tensor.numpy()    ----->>tensorflow to numpy

# Create a python list.
python_list = [1, 2]

# Create a NumPy array from the list.
numpy_array = np.array(python_list)

# Create a tensor from list.
tensor_from_list = tf.convert_to_tensor(python_list)

# Create a tensor from a NumPy array.
tensor_from_array = tf.convert_to_tensor(numpy_array)

# Create a NumPy array from a tensor.
array_from_tensor = tensor_from_array.numpy()

print('create python List:   ', python_list)
print('Numpy Array from list:  ', numpy_array)
print('Tensor from list: ', tensor_from_list)
print('Tensor from numpy array: ', tensor_from_array)
print('Numpy Array from tensor :  ', array_from_tensor)



create python List:    [1, 2]
Numpy Array from list:   [1 2]
Tensor from list:  tf.Tensor([1 2], shape=(2,), dtype=int32)
Tensor from numpy array:  tf.Tensor([1 2], shape=(2,), dtype=int64)
Numpy Array from tensor :   [1 2]


In [31]:
#test

import tensorflow as tf

# Assume we have a 2D TensorFlow array (tensor)
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# To access the element in the second row and third column (indexes start at 0)
element = tensor[1, 2]

print('element:',element.numpy())  # Output will be the scalar value 6

element: 6
