<a href="https://colab.research.google.com/github/DulanMahesh/ComputerVision/blob/main/Understanding_Array_deimesions_and_reshaping_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np



In [4]:
#Converting 1D Arrays to 2D Arrays

print('creating 1D array')
a= np.arange(1,13,dtype=int)

print(a)
print("a[0]   = ", a[0])


creating 1D array
[ 1  2  3  4  5  6  7  8  9 10 11 12]
a[0]   =  1


In [5]:
# reshape the 1D array into 2D array(1rows,12columns)

a=a.reshape(1,12)
print(a)
print("a[0]=",a[0])
print("a[0,6]=",a[0,6])

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
a[0]= [ 1  2  3  4  5  6  7  8  9 10 11 12]
a[0,6]= 7


In [6]:
# reshape again into 2D array (12 rows,1 columns)

a =a.reshape(12,1) #12rows ,1 column
print("Array:", a)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data Type:", a.dtype)
print("Number of Dimensions:", a.ndim)
print("Memory in Bytes:", a.nbytes)



Array: [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
Shape: (12, 1)
Size: 12
Data Type: int64
Number of Dimensions: 2
Memory in Bytes: 96


In [7]:
# Rehape the 1D array to a (3x4) 2D array.

a =a.reshape(3,4)
print("Array:" , a)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data Type:", a.dtype)
print("Number of Dimensions:", a.ndim)
print("Memory in Bytes:", a.nbytes)


Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Size: 12
Data Type: int64
Number of Dimensions: 2
Memory in Bytes: 96


In [8]:
a[2,3]

12

In [9]:
# reshaping multidimensional arrays

# create a (3 layers*5 rows in each layer*2 columns in each row) 3D array
b = np.array([
    [[10, 11], [10, 12], [10, 13], [10, 14], [10, 15]],
    [[20, 21], [20, 22], [20, 23], [20, 24], [20, 25]],
    [[30, 31], [30, 32], [30, 33], [30, 34], [30, 35]],])

print("Array:" , b)
print("Shape:", b.shape)
print("Size:", b.size)
print("Data Type:", b.dtype)
print("Number of Dimensions:", b.ndim)
print("Memory in Bytes:", b.nbytes)

Array: [[[10 11]
  [10 12]
  [10 13]
  [10 14]
  [10 15]]

 [[20 21]
  [20 22]
  [20 23]
  [20 24]
  [20 25]]

 [[30 31]
  [30 32]
  [30 33]
  [30 34]
  [30 35]]]
Shape: (3, 5, 2)
Size: 30
Data Type: int64
Number of Dimensions: 3
Memory in Bytes: 240


In [10]:
# now we reshape the previous array into (3,10) --it means weare going to flatten up the structure so it has only one layer ,3 rows where each row has 10 coloumns

b =b.reshape(3,10)

print("Array:",b)

Array: [[10 11 10 12 10 13 10 14 10 15]
 [20 21 20 22 20 23 20 24 20 25]
 [30 31 30 32 30 33 30 34 30 35]]


In [11]:
#Adding an Axis /Dimension

# here first we are going to create 1D array first

a =np.arange(1,10, dtype=int)
print("Array:", a)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data Type:", a.dtype)
print("Number of Dimensions:", a.ndim)
print("Memory in Bytes:", a.nbytes)


Array: [1 2 3 4 5 6 7 8 9]
Shape: (9,)
Size: 9
Data Type: int64
Number of Dimensions: 1
Memory in Bytes: 72


In [12]:
#create a 2D (3x3) array from the 1D array

a= a.reshape(3,3)
print("Array:", a)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data Type:", a.dtype)
print("Number of Dimensions:", a.ndim)
print("Memory in Bytes:", a.nbytes)


Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data Type: int64
Number of Dimensions: 2
Memory in Bytes: 72


In [13]:
#Add a new axis to the 3x3 array to create a 3D array
a=a.reshape(1,3,3)
print("Array:", a)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data Type:", a.dtype)
print("Number of Dimensions:", a.ndim)
print("Memory in Bytes:", a.nbytes)

Array: [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Shape: (1, 3, 3)
Size: 9
Data Type: int64
Number of Dimensions: 3
Memory in Bytes: 72


In [14]:
a[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a[0,1]

array([4, 5, 6])

In [16]:
a[0,1,2]

6

In [17]:
# expand dimensions - Here instead of reshape command we can use expand command to expand dimension

# Create a 1D array.
print('Create a 1D array:')
c = np.arange(1, 10, dtype=int)
print(c)
print("Shape:", c.shape)
print("Size:", c.size)
print("Data Type:", c.dtype)
print("Number of Dimensions:", c.ndim)
print("Memory in Bytes:", c.nbytes)

Create a 1D array:
[1 2 3 4 5 6 7 8 9]
Shape: (9,)
Size: 9
Data Type: int64
Number of Dimensions: 1
Memory in Bytes: 72


In [18]:
#reshape into 2D array(3*3 )

c=c.reshape(3,3)
print("Array:", c)
print("Shape:", c.shape)
print("Size:", c.size)
print("Data Type:", c.dtype)
print("Number of Dimensions:", c.ndim)
print("Memory in Bytes:", c.nbytes)

Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data Type: int64
Number of Dimensions: 2
Memory in Bytes: 72


In [20]:
c[2]

array([7, 8, 9])

In [25]:
#expand dimension using "np.expand_dims" command(here we can add more dimensions)

print('Using np.expand_dims:')
c_expanded = np.expand_dims(c,axis=0)
print(c_expanded)
print("Shape:", c_expanded.shape)
print("Size:", c_expanded.size)
print("Data Type:", c_expanded.dtype)
print("Number of Dimensions:", c_expanded.ndim)

Using np.expand_dims:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Shape: (1, 3, 3)
Size: 9
Data Type: int64
Number of Dimensions: 3


In [28]:
#squeeze

e = np.arange(1, 10, dtype=int)
e = e.reshape(1, 3, 3)
print(e)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [34]:
print("no of dimensions:",e)
print("array shape:",e.shape)

no of dimensions: [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
array shape: (1, 3, 3)


In [35]:
#squeeze or remove one dimension using "np.squeeze" command
print('Squeeze along axis=0:')
e_squeezed = np.squeeze(e,axis=0)
print(e_squeezed)
print("shape:",e_squeezed.shape)

Squeeze along axis=0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)


In [38]:
# reshape the array axel without specifing a length

f =np.arange(10)

print(f)


[0 1 2 3 4 5 6 7 8 9]


In [39]:
#reshape the array as two columns

f =f.reshape (-1,2)

print(f)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [43]:
#lets create a new array and reshape the array as two rows
#first create an array of 10 elements
g =np.arange(10)
print(g)



[0 1 2 3 4 5 6 7 8 9]


In [44]:
#now lets reshape the array as two rows

g =g.reshape(2,-1)
print(g)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [46]:
#Flattening arrays (to understand how images are processed in CNN -convolution neural network)

# Create three separate 4x4 arrays.
h1 = np.full((4, 4), 1, dtype='float32') # 4x4 array filled with 1s
h2 = np.full((4, 4), 2, dtype='float32')# 4x4 array filled with 2s
h3 = np.full((4, 4), 3, dtype='float32')# 4x4 array filled with 3s

# Create a 3x4x4 array.
h = np.zeros((3, 4, 4)) # 3dimension 4*4 array filled with zero


# Assign each 4x4 array to one "layer" in the 3D array
h[0] = h1  # First layer is filled with 1s
h[1] = h2 # second layer is filled with 2s
h[2] = h3 # third layer is filled with 3s

print(h)
print("Shape:", h.shape)
print("Size:", h.size)
print("Data Type:", h.dtype)
print("Number of Dimensions:", h.ndim)
print("Memory in Bytes:", h.nbytes)






[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]]
Shape: (3, 4, 4)
Size: 48
Data Type: float64
Number of Dimensions: 3
Memory in Bytes: 384


In [47]:

# reshape into 1D (3*16) to flatten the structure

h =h.reshape(3,16) # reshape into 3 rows and 16 columns per each row

print(h)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]]


In [71]:
#combining arrays

#concatanate

a1 = np.array([[1, 2, 3], [4, 5, 6]])
print("array a1:",a1)
print("shape:",a1.shape)
print("dimension:",a1.ndim)

a2 = np.array([[7, 8, 9]])
print("array a2:",a2)
print("shape:",a2.shape)
print("dimension:",a2.ndim)

a3= np.concatenate((a1,a2),axis=0) # concatanate a1 and a2
print("array a3:",a3)
print("Shape:", a3.shape)

print(" Dimensions:", a3.ndim)


array a1: [[1 2 3]
 [4 5 6]]
shape: (2, 3)
dimension: 2
array a2: [[7 8 9]]
shape: (1, 3)
dimension: 2
array a3: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
 Dimensions: 2


In [76]:
#Hstack (horizontal stack)
a1 = np.array([[1, 1, 1], [2, 2, 2]])
print("a1:",a1)
print("a1 shape:",a1.shape)
a2 = np.array([[3, 3, 3, 3], [4, 4, 4, 4]])
print("a2:",a2)
print("a2 shape:",a2.shape)

h_stacked =np.hstack((a1,a2))
print("horizontally stacked:",h_stacked)
print("Shape:", h_stacked.shape)

a1: [[1 1 1]
 [2 2 2]]
a1 shape: (2, 3)
a2: [[3 3 3 3]
 [4 4 4 4]]
a2 shape: (2, 4)
horizontally stacked: [[1 1 1 3 3 3 3]
 [2 2 2 4 4 4 4]]
Shape: (2, 7)


In [84]:
#another simple example for hstack
x =np.array ([[1],[2],[3]]) #array x with 3*1
print(x)
print("shape:",x.shape)
print("dimension:",x.ndim)


[[1]
 [2]
 [3]]
shape: (3, 1)
dimension: 2


In [88]:
y = np.array([[4],[5],[6]]) ##array y with 3*1
print(y)
print("shape:",y.shape)
print("dimension:",y.ndim)

[[4]
 [5]
 [6]]
shape: (3, 1)
dimension: 2


In [89]:
#now horizontal stacking for both x and y
h_stacked =np.hstack((x,y))
print("horizontally stacked:",h_stacked)
print("Shape:", h_stacked.shape)

horizontally stacked: [[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


In [93]:
#now lets try vertical stacking

a = np.array([[10],[20],[30]]) #2D array with 1*3
print(a)
print("shape:",a.shape)
print("dimension:",a.ndim)

[[10]
 [20]
 [30]]
shape: (3, 1)
dimension: 2


In [94]:
b =np.array([[40],[50],[60]])
print( b)
print("shape:",b.shape)
print("dimension:",b.ndim)

[[40]
 [50]
 [60]]
shape: (3, 1)
dimension: 2


In [97]:
#vertical stacking

z =np.vstack((a,b))
print("vertically stacked :" , z)
print("shape:",z.shape)
print("dimension:",z.ndim)

vertically stacked : [[10]
 [20]
 [30]
 [40]
 [50]
 [60]]
shape: (6, 1)
dimension: 2


In [101]:
# another example
# Create three separate 1x4x4 arrays.
h1 = np.full((1, 4, 4), 1, dtype='float32')


h2 = np.full((1, 4, 4), 2, dtype='float32')
h3 = np.full((1, 4, 4), 3, dtype='float32')

h = np.vstack((h1, h2, h3))

print(h)
print("Shape:", h.shape)
print("Size:", h.size)
print("Data Type:", h.dtype)
print("Number of Dimensions:", h.ndim)
print("Memory in Bytes:", h.nbytes)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]]
Shape: (3, 4, 4)
Size: 48
Data Type: float32
Number of Dimensions: 3
Memory in Bytes: 192
